extensions:
  commerce/backend-ui/1:
    operations:
      view:
        - type: web
          impl: index.html
    actions: actions
    web: web-src
    runtimeManifest:
      packages:
        starter-kit:
          license: Apache-2.0
          actions:
            # Please DO NOT DELETE this action; future functionalities planned for upcoming starter kit releases may stop working.
            info:
              function: actions/starter-kit-info/index.js
              web: 'yes'
              runtime: nodejs:22
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: true
                final: true
        customer-commerce:
          license: Apache-2.0
          actions:
            $include: ./actions/customer/commerce/actions.config.yaml
        customer-backoffice:
          license: Apache-2.0
          actions:
            $include: ./actions/customer/external/actions.config.yaml
        order-commerce:
          license: Apache-2.0
          actions:
            $include: ./actions/order/commerce/actions.config.yaml
        order-backoffice:
          license: Apache-2.0
          actions:
            $include: ./actions/order/external/actions.config.yaml
        admin-ui-sdk:
          license: Apache-2.0
          actions:
            registration:
              function: actions/registration/index.js
              web: 'yes'
              runtime: 'nodejs:22'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
        order-custom-grid-columns:
          license: Apache-2.0
          actions:
            get-order-grid-columns:
              function: actions/commerce-ui/orderGridColumns.js
              web: 'yes'
              runtime: 'nodejs:22'
              inputs:
                LOG_LEVEL: debug
              annotations:
                require-adobe-auth: false
                final: true
productDependencies:
  - code: COMMC
    minVersion: 2.4.4
    maxVersion: 3.0.0
